version: 2

sources:
  - name: coffee_shop
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - unique
              - not_null
 
      - name: orders
        columns:
          - name: id
            tests:
              - unique
              - not_null

models:
  - name: customers
    description: '{{ doc("customers") }}'
    tags: 'hi'